# Generated by Django 5.0 on 2024-11-09 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livestock_System', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_tag', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Breeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breeding_date', models.DateField()),
                ('expected_date', models.DateField()),
                ('success', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='father_breedings', to='Livestock_System.animal')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mother_breedings', to='Livestock_System.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('condition', models.CharField(max_length=100)),
                ('treatment', models.TextField()),
                ('veterinarian', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Livestock_System.animal')),
            ],
        ),
        migrations.DeleteModel(
            name='Livestock',
        ),
    ]
